import { mkdir } from "node:fs/promises";
import { join } from "node:path";
const root = join(import.meta.dir, "..");
await mkdir(join(root, ".generated"), { recursive: true });
const result = await Bun.build({
  entrypoints: [join(root, "src/web/app.tsx")],
  outdir: join(root, ".generated/web"),
  target: "browser",
  minify: true,
  define: { "process.env.NODE_ENV": JSON.stringify("production") },
  naming: { entry: "app.[ext]", asset: "[name].[ext]" },
});
if (!result.success) throw new Error(result.logs.join("\n"));
const html =
  '<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="color-scheme" content="dark"><title>Apex Highlight · 本地录像工作台</title><link rel="icon" href="data:,"><link rel="stylesheet" href="/app.css"></head><body><div id="root"></div><script src="/app.js" defer></script></body></html>';
const assets: Record<string, { type: string; body: string }> = {
  "/": { type: "text/html; charset=utf-8", body: html },
};
for (const output of result.outputs) {
  const extension = output.path.endsWith(".css") ? "css" : "js";
  assets[`/app.${extension}`] = {
    type:
      extension === "css"
        ? "text/css; charset=utf-8"
        : "text/javascript; charset=utf-8",
    body: await output.text(),
  };
}
await Bun.write(
  join(root, ".generated/assets.ts"),
  `// Generated by scripts/build-web.ts\nexport const assets = ${JSON.stringify(assets)};\n`,
);
console.log("网页资源已构建并准备嵌入主程序");
